### ISSUE TITLE
Open in-memory FS as RO?

### ISSUE THREAD

**Issue by gavanderhoorn** [nathanhi/pyfatfs#21]
4bbf04e02c05b7a060cf0616ff4f76348c1c3f4a adds support for in-memory, `io.BytesIO`-backed FS to be opened via the new `PyFatBytesIOFS(..)` constructor.

Would it be possible to allow opening such FS in *read-only* mode as well, similar to how the regular, file-backed `PyFatFS` allows that?

I'm using `pyfatfs` for forensic-like work, and being able to prevent any-and-all writes to images would be very handy to have.

**Comment by abrasive** [comment]
@gavanderhoorn I ran into the same exception, it should be fixed using #23

**Comment by gavanderhoorn** [comment]
Thanks.

**Comment by nathanhi** [comment]
> Edit 2: am I correct if I say that PyFatBytesIOFS and PyFat don't implement context management? It appears PyFatFS does, but that's not what I'm using.

PyFat [implements a context manager](https://github.com/nathanhi/pyfatfs/blob/master/pyfatfs/PyFat.py#L1015), PyFatFS and PyFatBytesIOFS are both implementing the PyFilesystem2 `FS` class, which provides a context manager:

```python
>>> from pyfatfs.PyFatFS import PyFatFS
>>> with PyFatFS("/dev/sda1.img", read_only=True) as fs:
...     print(fs.listdir("/"))
... 
/home/nathanhi/src/github/pyfatfs/pyfatfs/PyFat.py:237: UserWarning: Filesystem was not cleanly unmounted on last access. Check for data corruption.
['grub', 'EFI']
```
