### ISSUE TITLE
Files have correct date but no time

### ISSUE THREAD

**Issue by abrasive** [nathanhi/pyfatfs#22]
Hi, thanks for the fantastic tool!

I'm having a bit of trouble with `__combine_dosdatetime` in `FATDirectoryEntry.py`. It combines the date and time, but it doesn't return the result of the `.combine()` call, instead returning the (unmodified) `dt`.

I can fix this for my use case by changing it to
```
        return dt.combine(dt, DosDateTime.deserialize_time(tm))
```
but I think this makes it return a `datetime.datetime` instead of a `DosDateTime`; what do you think is the correct fix?

**Comment by nathanhi** [comment]
Yes, this is indeed a bug and instead the newly created `DosDateTime` class instance returned by the `combine` call should be returned. Fixed in v1.0.3.

**Comment by abrasive** [comment]
My bad, the type inference indicated it returned a datetime.datetime so my 
language server was complaining! Works perfectly for me.

Thanks for cutting a new release so quickly, much appreciated 🙏🏻

**Comment by nathanhi** [comment]
Awesome, thanks for verifying!
