### ISSUE TITLE
Is `PyFatFS.setinfo()` "Not yet properly implemented" docstring outdated?

### ISSUE THREAD

**Issue by dcoshea** [nathanhi/pyfatfs#27]
`PyFatFS.setinfo()` is documented as "Not yet properly implemented", but at least for setting the `modified` time, it seems to work apart from issue #26 meaning that the value read back can be wrong if `minutes > 31`.  Is that docstring outdated, or are you able to provide more information about what problems I should expect if I try to use it?

**Comment by nathanhi** [comment]
Thank you for letting me know. It is feature complete - I updated the docstring in 1.0.4!
