### ISSUE TITLE
release new version

### ISSUE THREAD

**Issue by nioncode** [nathanhi/pyfatfs#38]
The last released version (v1.0.5) is from April 2022. Would you mind releasing a new version and pushing it to pypi?

We need the fix of b83f27ce6325f99138eefd6e924497aa53c7ac9d (which interestingly is not part of v1.0.5, because the release apparently happened on a different branch), so we pin the first commit after merging the v1.0.5 branch back into master (d5f123d6cd2dcbfe2ed36f5a67aa1257d33a48c0).

However, it would be great if we could could pin to an official version instead of a random commit.

**Comment by nathanhi** [comment]
I'll be preparing a 1.1.0 release soon, please follow this discussion to stay up to date:

https://github.com/nathanhi/pyfatfs/discussions/37#discussioncomment-8657109

**Comment by nathanhi** [comment]
1.1.0 has just been released 🎉
