### ISSUE TITLE
running error: protocol 'fat' is not supported

### ISSUE THREAD

**Issue by beewu** [nathanhi/pyfatfs#43]
Hello,
I package the exe file through the installer, running error: protocol 'fat' is not supported, but running the program directly does not report errors. After the exe file is packaged, the program cannot find entry_points. How can I solve this problem?
![3b881777ac794ae75fba0cb9897d533](https://github.com/user-attachments/assets/7e0467f5-72c5-4ab2-94fb-7b20f2a3ffc6)

**Comment by nathanhi** [comment]
I presume this is related to #10 and likely a limitation of PyFilesystem2's protocol handler when freezing a binary. I recommend instantiating `PyFatFS` directly since PyFilesystem2 seems to be unmaintained anyway.
